### ISSUE TITLE
[feat] Before/After class and method decorators

### ISSUE THREAD

**Issue by leeuwis** [storyofams/next-api-decorators#117]
Having an `@Authorize` decorator that can be added to a class (which will apply it to all methods) or to specific methods within a class. The developer should be able to apply its own auth logic when using the decorator. This logic will most likely be based on `req`, e.g. verifying a JWT in a cookie or validating a bearer token in the authorization header.

**Comment by ggurkal** [comment]
I think, implementing a middleware layer via decorators would be more beneficial and can leverage authentication as well. It will also be compatible with most express.js middlewares I believe.

**Comment by leeuwis** [comment]
@ggurkal do you mean like a `@Before` decorator?

**Comment by ggurkal** [comment]
Yes. So, the following can be valid usage:

```ts
function AuthorizationMiddleware(req, res, next) {
  if (jwtValidationCheck(req)) {
    return next();
  }

  return next(new UnauthorizedException());
  // or
  throw new UnauthorizedException();
}

function LoggerMiddleware(...) { ... }

@Before(LoggerMiddleware, AuthorizationMiddleware)
class PrivateListHandler {
  @Get()
  public list() { ... }
}
```

---

Naming wise, if we're not going to have `Before` and `After`, I'd go for `UseMiddleware`. What are your thoughts on this?

**Comment by Dev-CasperTheGhost** [comment]
This would be a cool and useful feature!

**Comment by leeuwis** [comment]
@ggurkal I think it would be nice to also be able to use `After` for things like file clean after uploads or triggering a specific function after it succeeded (e.g. sending a Slack message). Since the response has already been handled before the `After`, someone should normally not throw in the `After`. So the logic between the `Before` and `After` should probably be a bit different (e.g. no `next` param in the `After` function).

**Comment by leeuwis** [comment]
@ggurkal and it being compatible with most express middleware functions it pretty powerful 😮
