### ISSUE TITLE
[Feature request] Allow Custom Parameter Decorators to Accept Arguments

### ISSUE THREAD

**Issue by tn12787** [storyofams/next-api-decorators#249]
Hey guys, thanks for making this great library! 😄 

**Is your feature request related to a problem? Please describe.**
Currently, it doesn't seem possible to create parameter decorators that accept arguments.

My specific use case is:

I'm not using express-style route matching (relying on `Next`'s file-based structure), and I'd like to build a custom decorator to let me do something like `Param()`, which doesn't work without the express-style route matching it seems.

**Describe the solution you'd like**
I'd like to propose that createParamDecorator can accept functions with more than one argument, something like this:

```ts
export const PathParam = createParamDecorator<string | undefined>(
  (req, key) => req.query[key] as string | undefined
);
```

which I could then use as:

```ts
async listItemData(@PathParam('id') id: string | undefined
```

**Describe alternatives you've considered**
I'm working around this currently without a decorator but it'd be great to use decorators for everything, as I'm using them for my whole API otherwise 🙌

**Comment by ggurkal** [comment]
Hi @tn12787 ,

Thank you for your interest in the library!

It is possible to create parameter decorators in a way you like:

```ts
export const PathParam = (key: string) => createParamDecorator(
  req => req.query[key]
)();
```

However, you can already use the `@Query` decorator for your use case, as Next.js injects file name parameters into the `req.query` object.

**Comment by tn12787** [comment]
Amazing, Thanks for the swift reply! That's exactly what I was hoping 😄
