### ISSUE TITLE
Endpoint doesn't work in production on Vercel

### ISSUE THREAD

**Issue by abriginets** [storyofams/next-api-decorators#262]
**Describe the bug**
Hello. I've created an endpoint and it's working on `npm run dev` and on `npm run build && npm run start` locally. But when I deploy it on Vercel it returns `{"statusCode":404,"message":"Cannot GET /api/image/airline/regular/256/BT","error":"Not Found"}` though in build logs I see it's being successfully located and built:
```
├ λ /api/image/[[...params]]           0 B            95.6 kB
```
How could I debug this behavior?

**To Reproduce**
```ts
import { createHandler, Get, Param, ParseNumberPipe, SetHeader } from '@storyofams/next-api-decorators';

import { serveDynamicImage } from '../../../src/server/services/airline-image/airline-image.service';
import { AirlineImageTypesEnum } from '../../../src/server/services/airline-image/enums/airline-image.enums';

class ImageController {
  @SetHeader('Content-Type', 'image/png')
  @Get('/airline/:type/:width/:iata')
  async getAirlineImage(
    @Param('type') type: AirlineImageTypesEnum,
    @Param('width', ParseNumberPipe) width: number,
    @Param('iata') iata: string,
  ) {
    return await serveDynamicImage(type, width, iata);
  }
}

export default createHandler(ImageController);

```

**Expected behavior**
It should deploy to Vercel and be usable in there.

**Desktop (please complete the following information):**
 - OS: WIndows 10 WSL2 (Ubuntu 20.04)
 - Browser Chrome
 - Version 93

**Comment by abriginets** [comment]
Does it makes sense to add new decorator `@Debugger()` for classes with optional argument that accepts different log levels? This way I could debug my application in prod on Vercel using log drains and provide you with more comprehensive details.

**Comment by ggurkal** [comment]
Hey @abriginets 

Thanks for reporting the bug and the input on debugging! A fix is on the way for the bug.

Regarding debugging:
I think it makes more sense to add an environment variable for debugging purposes. Will take it into consideration for future releases.

**Comment by valentintorres02** [comment]
Hi! It seems I'm having a similar problem...

My routes are working fine at localhost (next dev and next start). But when I deploy everything to Vercel, I have an [promptId].ts endpoint that returns a 404 error (and it's just a blank response, I'm not even getting the next html error page)

The other routes without params work fine. My code:

```
// pages/api/prompt/[promptId].ts
import { PromptService } from "api/services/prompt.service";
import { EditPromptInput } from "common/dto/prompt";
import {
  Body,
  createHandler,
  Delete,
  HttpCode,
  Param,
  Patch,
  ValidationPipe,
} from "next-api-decorators";

class PromptRoutes {
  private readonly promptService: PromptService;

  constructor() {
    this.promptService = new PromptService();
  }
  
  @Delete("/:promptId")
  @HttpCode(200)
  public async delete(@Param("promptId") promptId: string) {
    const deletedPrompt = await this.promptService.delete(parseInt(promptId));

    return deletedPrompt;
  }

  @Patch("/:promptId")
  @HttpCode(200)
  public async edit(
    @Param("promptId") promptId: string,
    @Body(ValidationPipe) body: EditPromptInput
  ) {
    const data = body;
    const editedPrompt = await this.promptService.edit(parseInt(promptId), data);

    return editedPrompt;
  }
}

export default createHandler(PromptRoutes);

```

I have `path-to-regexp` v6.2.1 installed.

ts.config.json:

```
{
  "compilerOptions": {
    "target": "es6",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "experimentalDecorators": true,
    "jsx": "preserve",
    "incremental": true,
    "baseUrl": ".",
    "paths": {
      "@components/*": ["components/*"],
      "@styles/*": ["styles/*"],
      "@hooks/*": ["hooks/*"],
      "@interfaces/*": ["interfaces/*"],
      "@images/*": ["public/images/*"],
      "@content/*": ["content/*"],
      "@lib/*": ["lib/*"],
      "@pages/*": ["pages/*"]
    },
    "emitDecoratorMetadata": true
  },
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx"],
  "exclude": ["node_modules"]
}

```

 I have a standard Next.js app with standard Vercel deploy. Please let me know if you need any more data. Thanks in advance =)

Example request that works on localhost and does not work on vercel:

URL: https://twitter-automated-bot.vercel.app/api/prompt/14 
BODY: `{"priority": 0, "text": "something"}`
