### ISSUE TITLE
Cannot read property 'referencePaths' of undefined

### ISSUE THREAD

**Issue by BJvdA** [storyofams/next-api-decorators#27]
**Describe the bug**
`babel-plugin-parameter-decorator` causes an error with React v17, seems like it does not support the new jsx runtime. See [this issue](https://github.com/WarnerHooh/babel-plugin-parameter-decorator/issues/25).

Error:
```
Cannot read property 'referencePaths' of undefined
    at transformFile.next (<anonymous>)
    at run.next (<anonymous>)
```

**To Reproduce**
Use create-next-app and add the babel config, run it, and open any page.

**Comment by ggurkal** [comment]
Can you share your `.babelrc`?

**Comment by BJvdA** [comment]
I made a minimum reproducible example: [here](https://github.com/BJvdA/babel-plugin-parameter-decorator-bug/)
Turns out it's because of `@styled-system/css` 🙄

**Comment by ggurkal** [comment]
Creating a separate babel config file for API routes under `pages/api` folder and putting the decorator plugins there fixes the problem.
