### ISSUE TITLE
Using @Param or @Query causes handler to throw error due to missing Reflect metadata for "design:paramtypes"

### ISSUE THREAD

**Issue by sannajammeh** [storyofams/next-api-decorators#320]
**Describe the bug**
When using the @Param or @Query decorator,  a TypeError occurs because `const parameterTypes` in `internals/handler.ts` is undefined. This line specifically seems to create the issue:

```ts
const parameterTypes: ClassConstructor<any>[] = Reflect.getMetadata('design:paramtypes', target, propertyKey); // Line 70 in handler.ts
```

**To Reproduce**
1. run `npx create-next-app --ts` and enable typescript decorator support
2. Add this library to an api route with path-to-regexp installed
3. Use the @Param(":someId") decorator.
```json
{
  "statusCode": 500,
  "message": "An unknown error occurred.",
  "errors": [
    "An unknown error occurred."
  ],
  "stack": "TypeError: Cannot read property 'length' of undefined\n    at /Users/sannajammeh/code/Cartable/CourseExposure/platform/node_modules/@storyofams/next-api-decorators/dist/internals/handler.js:45:50\n    at Array.map (<anonymous>)\n    at StudioController.runMainLayer (/Users/sannajammeh/code/Cartable/CourseExposure/platform/node_modules/@storyofams/next-api-decorators/dist/internals/handler.js:41:62)\n    at StudioController.descriptor.value (/Users/sannajammeh/code/Cartable/CourseExposure/platform/node_modules/@storyofams/next-api-decorators/dist/internals/handler.js:105:32)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async Object.apiResolver (/Users/sannajammeh/code/Cartable/CourseExposure/platform/node_modules/next/dist/server/api-utils.js:102:9)\n    at async DevServer.handleApiRequest (/Users/sannajammeh/code/Cartable/CourseExposure/platform/node_modules/next/dist/server/next-server.js:1064:9)\n    at async Object.fn (/Users/sannajammeh/code/Cartable/CourseExposure/platform/node_modules/next/dist/server/next-server.js:951:37)\n    at async Router.execute (/Users/sannajammeh/code/Cartable/CourseExposure/platform/node_modules/next/dist/server/router.js:222:32)\n    at async DevServer.run (/Users/sannajammeh/code/Cartable/CourseExposure/platform/node_modules/next/dist/server/next-server.js:1135:29)"
}
```

5. Enter node_modules folder and change line 45 in `@storyofams/next-api-decorators/dist/internals/handler.js`
```diff
-         const paramType = index < parameterTypes.length &&
+        const paramType = index < parameterTypes?.length &&
```
6. Observe that the API route now works.

**Expected behavior**
The `parameterTypes` should not be undefined.

**Desktop (please complete the following information):**
 - OS: Mac OS 11.5.2
 - Server: Next JS 12 compiled with SWC with decorators enabled
 - Version 1.6.0

![image](https://user-images.githubusercontent.com/50969683/147794590-6a9c910b-8cb8-45a8-a6a9-9e16262c4b71.png)

**Additional context**
Everything works without using the Param or Query decorators.

**Comment by mitchelvanbever** [comment]
Have you setup babel or are you using SWC for compilation? I believe the package still relies on the usage of babel to provide the decorators API (legacy)

**Comment by sannajammeh** [comment]
> Have you setup babel or are you using SWC for compilation? I believe the package still relies on the usage of babel to provide the decorators API (legacy)
> 
> See: https://next-api-decorators.vercel.app/docs/

I believe this can be closed. Submitted a PR to Next.JS which supports decoratorMetadata in SWC.
