### ISSUE TITLE
Error after upgrading to Next 12.0.9 

### ISSUE THREAD

**Issue by martinmilsomce** [storyofams/next-api-decorators#352]
**Describe the bug**
All endpoints return a 500 error after upgrading to Next 12.0.9 (from 12.0.8). 
`TypeError: Cannot read properties of undefined (reading 'replace')`

**To Reproduce**
1. Create a new next app (ensure "next" version is 12.0.9)
2. Create a simple controller in `pages/api` 
```
// pages/api/hello.ts
class HelloWorld {
  @Get()
  async get(): Promise<any> {
    return {
      Hello: "Hello, world!",
    };
  }
}

export default createHandler(HelloWorld);
```
3. call the endpoint using fetch `/api/hello`
4. All calls give a 500 response
5. Call stack:
```
Object.parseRequestUrl
file:///C:/code/test/node_modules/@storyofams/next-api-decorators/dist/internals/parseRequestUrl.js (16:54)
<unknown>
file:///C:/code/test/node_modules/@storyofams/next-api-decorators/dist/createHandler.js (35:40)
Object.apiResolver
file:///C:/code/test/node_modules/next/dist/server/api-utils.js (101:15)
runMicrotasks
<anonymous>
processTicksAndRejections
node:internal/process/task_queues (96:5)
async DevServer.runApi
file:///C:/code/test/node_modules/next/dist/server/next-server.js (319:9)
async Object.fn
file:///C:/code/test/node_modules/next/dist/server/base-server.js (486:37)
async Router.execute
file:///C:/code/test/node_modules/next/dist/server/router.js (228:32)
async DevServer.run
file:///C:/code/test/node_modules/next/dist/server/base-server.js (598:29)
async DevServer.run
file:///C:/code/test/node_modules/next/dist/server/dev/next-dev-server.js (444:20)
```

**Expected behavior**
Endpoint returns "Hello, world" & 200.

**Desktop (please complete the following information):**
 - OS: W11
 - Browser: Chrome
 - Version 97

**Additional context**
Downgrading back down to 12.0.8 solves the issue with no code changes

**Comment by ggurkal** [comment]
Thanks for the report! v1.7.1 should fix this problem.
