### ISSUE TITLE
Next 12 SWC Support

### ISSUE THREAD

**Issue by tn12787** [storyofams/next-api-decorators#356]
**Is your feature request related to a problem? Please describe.**
Some of the babel features we need to use decorators aren't supported by [SWC ](https://swc.rs/) yet.

This is the current required babel config:

```ts
{
  "plugins": [
    "babel-plugin-transform-typescript-metadata",
    ["@babel/plugin-proposal-decorators", { "legacy": true }],
    "babel-plugin-parameter-decorator",
    // ... other plugins
  ]
}
```

**Describe the solution you'd like**
Is there a workaround that'd let us support Next 12?

**Describe alternatives you've considered**
It's not broken as-is, by any means, we just can't enjoy the benefits of native toolchains yet.

**Comment by Dev-CasperTheGhost** [comment]
*probably not the most helpful comment* but there's a PR open that is related to this: https://github.com/vercel/next.js/pull/32914.

**Comment by sannajammeh** [comment]
`yarn add next@canary` should resolve this now :)

Keep in mind you'll be installing a pre-release NextJS

**Comment by tn12787** [comment]
Amazing! Thanks @sannajammeh for the feature and @Dev-CasperTheGhost for the update 🎉 🚀

**Comment by sannajammeh** [comment]
> I tried the above out, but I'm still getting an issue with:
> 
> 
> 
> > Support for the experimental syntax 'decorators-legacy' isn't currently enabled
> 
> 
> 
> Has anyone had a solution to that? Sounds like it's eslint related?

Had a similar issue while working on the PR in for decorator support in Next.js. If my memory serves me right this was an eslint issue.
