### ISSUE TITLE
Testing API Routes

### ISSUE THREAD

**Issue by tn12787** [storyofams/next-api-decorators#379]
**Is your feature request related to a problem? Please describe.**
I'm thinking about how to approach testing API routes built with this lib. With the older functional style I'd test API routes [like this](https://seanconnolly.dev/unit-testing-nextjs-api-routes), but that's a little harder with the decorators and classes.

**Describe the solution you'd like**
Any thoughts or pointers on a good approach. Once again, thanks for this awesome library!

**Comment by ggurkal** [comment]
You can do it in the same way! The only difference is to pass the `url` property correctly. This is a test that I sketched now for `/examples/route-matching/pages/api/users/[[...params]].ts`:

```ts
import { createMocks } from 'node-mocks-http';
import handleUsers from './[[...params]]';

describe('/api/users/[[...params]]', () => {
  test('Fetches a user', async () => {
    const { req, res } = createMocks({
      method: 'GET',
      url: '/api/users/101',
    });

    await handleUsers(req, res);

    expect(res._getStatusCode()).toBe(200);
    expect(res._getData()).toEqual(
      expect.objectContaining({
        id: 101,
      }),
    );
  });

  test('Returns 404', async () => {
    const { req, res } = createMocks({
      method: 'GET',
      url: '/api/users/101111',
    });

    await handleUsers(req, res);

    expect(res._getStatusCode()).toBe(404);
    expect(JSON.parse(res._getData())).toEqual(
      expect.objectContaining({
        message: "No user found with ID '101111'.",
      }),
    );
  });
});
```

**Comment by tn12787** [comment]
Amazing, thank you!

**Comment by tn12787** [comment]
@ggurkal I followed your example, some simple tests worked great!

However, it seems to be a little tricky to get route matching to work.

I can't get a request to a page like `pages/api/something/[id]`, keep getting 

```json
 {"statusCode":404,"message":"Cannot GET /api/something/test","error":"Not Found"}
```

when i try creating a mock like:

```ts
const testId = 'test';
const { req, res } = createMocks({
  method: 'GET',
  url: `/api/something/${testId}`,
  query: {
    id:  testId,
  },
  params: {
    id testId,
  },
});
```

Despite the fact that the API route exists and works in production 😟

**Comment by ggurkal** [comment]
Hey @tn12787 

Sorry for the late reply, been quite busy lately.

What's the full path of your handler file? I just tested the mock you posted above with a file`pages/api/page/[id].ts` and worked without any issues.
