### ISSUE TITLE
[docs] Add instructions for usage with SWC

### ISSUE THREAD

**Issue by mprasanjith** [storyofams/next-api-decorators#381]
**Is your feature request related to a problem? Please describe.**
Currently the documentation only details instructions for usage with Babel. This library seems to be working fine now with SWC as well, although with a bunch of additional configs.

**Describe the solution you'd like**
Please add setup instructions on how to use this library with SWC.

**Describe alternatives you've considered**
None

**Additional context**
Thanks for this awesome library!

**Comment by wescopeland** [comment]
For anyone stumbling across this issue, all that is required is in your _tsconfig.json_, add these lines inside of "compilerOptions":

```json
"experimentalDecorators": true,
"emitDecoratorMetadata": true,
```
