### ISSUE TITLE
Example Setting Variables On Middleware Decorators

### ISSUE THREAD

**Issue by anthonyalayo** [storyofams/next-api-decorators#411]
**Is your feature request related to a problem? Please describe.**
I have been following the docs here for setting custom middleware:
https://next-api-decorators.vercel.app/docs/middlewares

My use case is exactly the same -- some sort of jwt auth guard -- but I would like to set a variable to forward the user to the next api/middleware in the chain. How can I do this in TypeScript?

**Describe the solution you'd like**
Updated docs to describe how to forward auth user info.

**Comment by ggurkal** [comment]
You can see a basic example here https://github.com/storyofams/next-api-decorators/blob/master/examples/with-next-auth/pages/api/users/%5B%5B...params%5D%5D.ts

**Comment by anthonyalayo** [comment]
Thanks!
