### ISSUE TITLE
Support for query objects

### ISSUE THREAD

**Issue by hrougier** [storyofams/next-api-decorators#418]
Coming from NestJS, you have the ability to use serialized objects in query strings (described in Swagger as [deepObjects](https://swagger.io/docs/specification/serialization/)), such as 

```
/api/users?where[firstname]=john&where[lastname]=doe

// @Query('where') then contains
where: {
  firstname: "john",
  lastname: "doe"
}


/api/users?where[date][gte]=2022-05-17&where[date][lte]=2022-05-18

// @Query('where') then contains
where: {
  date: {
    gte: "2022-05-17",
    lte: "2022-05-18"
  }
}
```

**Describe the solution you'd like**

Currently, `@Query` decorator only supports simple strings, deep objects return undefined

```
/api/users?where[date][gte]=2022-05-17

// @Query('where') then contains
undefined
```

Seems to be a NextJS issue itself? Would be nice to have a more powerfurl `@Query` decorator to handle such use cases, any idea?

**Comment by ggurkal** [comment]
Indeed, Next.js doesn't have it built-in. However, Express.js (also NestJS, if you're using Express.js with it) makes use of the `qs` package for this functionality.

If you're using `qs` anyway, you can have it as a middleware to parse the query. Here is a middleware:

```ts
@UseMiddleware((req: NextApiRequest, _: NextApiResponse, next: NextFunction) => {
  req.query = parse(req.query as Record<string, any>) as typeof req.query;
  return next();
})
```

Types don't match but seems to work just fine.
