### ISSUE TITLE
Dynamic Routes don't Match Sub-Routes when the Parameter Value Contains Hyphens

### ISSUE THREAD

**Issue by tn12787** [storyofams/next-api-decorators#434]
**Describe the bug**

Basically, when we're using an API route at something like `pages/api/posts/[slug]/meta`:

If the value of `slug` contains hyphens, e.g. `my-first-post`, then any sub-routes (like `meta` in this case) no longer match

**To Reproduce**

1. Create an API route at  `pages/api/posts/[slug]/meta` with a simple GET handler.
2. Try sending a request when the value of `slug` is 'help-me'
3. You get "Cannot GET /api/lessons/help-me/meta"
4. Note: if you change this to `helpme`, the route matches.

**Expected behavior**
A route should match.

**Comment by ggurkal** [comment]
Hi @tn12787 

Thanks for the bug report! Just released a fix in the `beta` channel.

Let me know the outcome.

**Comment by tn12787** [comment]
Thanks so much! I'll give it a go and report back :)

**Comment by tn12787** [comment]
Looks fixed! Think we can close this :)

**Comment by tn12787** [comment]
Thanks for the speedy fix!
