### ISSUE TITLE
Doesn't work with native rewrites of NextJS

### ISSUE THREAD

**Issue by abriginets** [storyofams/next-api-decorators#436]
**Describe the bug**
For some reason it is possible to rewrite request path to next-api-decorators but it's reading the old path instead of rewritten one.

**To Reproduce**
Create match-all slug under `pages/api/[[...slug]].ts` and then create a rewrite rule in NextJS config:
```ts
/** @type {import('next').NextConfig} */
const nextConfig = {
  async rewrites() {
    return {
      beforeFiles: [
        {
          source: '/assets/image/airline/:type/:width/:iata.:extension',
          destination: '/api/image/airline/type/:type/width/:width/code/:iata/extension/:extension',
        },
      ],
    };
  },
};

module.exports = nextConfig;
```
Try to access the `/assets/image/airline/:type/:width/:iata.:extension` path and you'll see the error
```
{"statusCode":404,"message":"Cannot GET /assets/image/airline/al_square/500/SU.webp","error":"Not Found"}
```

So it seems like rewrite was successfully applied but next-api-decorators are reading the original url path instead of new one.

**Expected behavior**
It should read the new path that was applied after rewrite.

**Comment by ggurkal** [comment]
Hi @abriginets 

A fix is release under the `beta` channel. Let me know if it works for you.

**Comment by abriginets** [comment]
@ggurkal yep. that works!
