### ISSUE TITLE
ValidationPipe ignores empty body 

### ISSUE THREAD

**Issue by impez** [storyofams/next-api-decorators#441]
```
class RegisterDTO {
  @IsEmail()
  email: string;

  @IsNotEmpty()
  @IsString()
  @Length(6, 64)
  password: string;
}

class AuthController{
  @Post("/register")
  @HttpCode(201)
    public register(@Body(ValidationPipe) body: RegisterDTO) {
      return AuthService.register(body);
    }
}
```

When I'm hitting POST `/register` endpoint with Postman (empty body) validation doesn't run and I get 200. If I declare something like `{}` validation works just fine and it requires mentioned values like email and password. Am I missing something?

**Comment by ggurkal** [comment]
Hi @impez 

Thanks for the report. A fix has been released.
